title: Sacramento Urban Technology Lab
description: Accelerating quality of life for all Sacramentans through data-driven testing and experimentation.
url: https://sutl.innovatesac.org
logo: /img/favicon.jpg
twitter_username: innovatesac
github_username:  innovatesac

jekyll_analytics:
  GoogleAnalytics:          # Add, if you want to track with Google Analytics
    id: UA-97991361-3       # Required - replace with your tracking id
    anonymizeIp: false      # Optional - Default: false - set to true for anonymized tracking

plugins:
  - jekyll-seo-tag
  - jekyll-analytics

permalink: pretty

defaults:
  - scope:
      path: ""
    values:
      image: /img/sut-cover.jpg


# Server Config options
# livereload: true     # You no longer need to include --livereload
